#include "f2c.h"
#include <tcl.h>
MODULE_SCOPE /* Subroutine */ int dgesdd_ (Tcl_Interp *interp, char *jobz, integer *m, integer *n, doublereal *	a, integer *lda, doublereal *s, doublereal *u, integer *ldu, 	doublereal *vt, integer *ldvt, doublereal *work, integer *lwork, 	integer *iwork, integer *info);
MODULE_SCOPE /* Subroutine */ int zgesdd_ (Tcl_Interp *interp, char *jobz, integer *m, integer *n, 	doublecomplex *a, integer *lda, doublereal *s, doublecomplex *u, 	integer *ldu, doublecomplex *vt, integer *ldvt, doublecomplex *work, 	integer *lwork, doublereal *rwork, integer *iwork, integer *info);
MODULE_SCOPE /* Subroutine */ int dgemm_ (Tcl_Interp *interp, char *transa, char *transb, integer *m, integer *	n, integer *k, doublereal *alpha, doublereal *a, integer *lda, 	doublereal *b, integer *ldb, doublereal *beta, doublereal *c__, 	integer *ldc);
MODULE_SCOPE /* Subroutine */ int zgemm_ (Tcl_Interp *interp, char *transa, char *transb, integer *m, integer *	n, integer *k, doublecomplex *alpha, doublecomplex *a, integer *lda, 	doublecomplex *b, integer *ldb, doublecomplex *beta, doublecomplex *	c__, integer *ldc);
MODULE_SCOPE /* Subroutine */ int dsyevr_ (Tcl_Interp *interp, char *jobz, char *range, char *uplo, integer *n, 	doublereal *a, integer *lda, doublereal *vl, doublereal *vu, integer *	il, integer *iu, doublereal *abstol, integer *m, doublereal *w, 	doublereal *z__, integer *ldz, integer *isuppz, doublereal *work, 	integer *lwork, integer *iwork, integer *liwork, integer *info);
MODULE_SCOPE /* Subroutine */ int zheevr_ (Tcl_Interp *interp, char *jobz, char *range, char *uplo, integer *n, 	doublecomplex *a, integer *lda, doublereal *vl, doublereal *vu, 	integer *il, integer *iu, doublereal *abstol, integer *m, doublereal *	w, doublecomplex *z__, integer *ldz, integer *isuppz, doublecomplex *	work, integer *lwork, doublereal *rwork, integer *lrwork, integer *	iwork, integer *liwork, integer *info);
MODULE_SCOPE /* Subroutine */ int dgeev_ (Tcl_Interp *interp, char *jobvl, char *jobvr, integer *n, doublereal *	a, integer *lda, doublereal *wr, doublereal *wi, doublereal *vl, 	integer *ldvl, doublereal *vr, integer *ldvr, doublereal *work, 	integer *lwork, integer *info);
MODULE_SCOPE /* Subroutine */ int zgeev_ (Tcl_Interp *interp, char *jobvl, char *jobvr, integer *n, 	doublecomplex *a, integer *lda, doublecomplex *w, doublecomplex *vl, 	integer *ldvl, doublecomplex *vr, integer *ldvr, doublecomplex *work, 	integer *lwork, doublereal *rwork, integer *info);
MODULE_SCOPE /* Subroutine */ int dgelss_ (Tcl_Interp *interp, integer *m, integer *n, integer *nrhs, 	doublereal *a, integer *lda, doublereal *b, integer *ldb, doublereal *	s, doublereal *rcond, integer *rank, doublereal *work, integer *lwork, 	 integer *info);
MODULE_SCOPE /* Subroutine */ int zgelss_ (Tcl_Interp *interp, integer *m, integer *n, integer *nrhs, 	doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, 	doublereal *s, doublereal *rcond, integer *rank, doublecomplex *work, 	integer *lwork, doublereal *rwork, integer *info);
MODULE_SCOPE /* Subroutine */ int dgelsy_ (Tcl_Interp *interp, integer *m, integer *n, integer *nrhs, 	doublereal *a, integer *lda, doublereal *b, integer *ldb, integer *	jpvt, doublereal *rcond, integer *rank, doublereal *work, integer *	lwork, integer *info);
MODULE_SCOPE /* Subroutine */ int zgelsy_ (Tcl_Interp *interp, integer *m, integer *n, integer *nrhs, 	doublecomplex *a, integer *lda, doublecomplex *b, integer *ldb, 	integer *jpvt, doublereal *rcond, integer *rank, doublecomplex *work, 	integer *lwork, doublereal *rwork, integer *info);
MODULE_SCOPE /* Subroutine */ int dgesv_ (Tcl_Interp *interp, integer *n, integer *nrhs, doublereal *a, integer 	*lda, integer *ipiv, doublereal *b, integer *ldb, integer *info);
MODULE_SCOPE /* Subroutine */ int zgesv_ (Tcl_Interp *interp, integer *n, integer *nrhs, doublecomplex *a, 	integer *lda, integer *ipiv, doublecomplex *b, integer *ldb, integer *	info);
MODULE_SCOPE /* Subroutine */ int dgesvx_ (Tcl_Interp *interp, char *fact, char *trans, integer *n, integer *	nrhs, doublereal *a, integer *lda, doublereal *af, integer *ldaf, 	integer *ipiv, char *equed, doublereal *r__, doublereal *c__, 	doublereal *b, integer *ldb, doublereal *x, integer *ldx, doublereal *	rcond, doublereal *ferr, doublereal *berr, doublereal *work, integer *	iwork, integer *info);
MODULE_SCOPE /* Subroutine */ int zgesvx_ (Tcl_Interp *interp, char *fact, char *trans, integer *n, integer *	nrhs, doublecomplex *a, integer *lda, doublecomplex *af, integer *	ldaf, integer *ipiv, char *equed, doublereal *r__, doublereal *c__, 	doublecomplex *b, integer *ldb, doublecomplex *x, integer *ldx, 	doublereal *rcond, doublereal *ferr, doublereal *berr, doublecomplex *	work, doublereal *rwork, integer *info);

